'use strict'

 //--------------------------------------------- 
 // Copyright(c) 2015 SunshinyNeko Written by VSCode
 //--------------------------------------------- 

const AUTHENTICATION = { 
  NOAUTH: 0x00,
  GSSAPI: 0x01,
  USERPASS: 0x02,
  NONE: 0xFF
};

const REQUEST_CMD = {
  CONNECT: 0x01,
  BIND: 0x02,
  UDP_ASSOCIATE: 0x03
};

const ATYP = {
  IPV4: 0x01,
  DN: 0x03,
  IPV6: 0x04
};

const REPLY_CODE = {
  SUCCESS: 0x00,
  SOCKS_SERVER_FAILURE: 0x01,
  CONNECTION_NOT_ALLOWED: 0x02,
  NETWORK_UNREACHABLE: 0x03,
  HOST_UNREACHABLE: 0x04,
  CONNECTION_REFUSED: 0x05,
  TTL_EXPIRED: 0x06,
  CMD_NOT_SUPPORTED: 0x07,
  ADDR_TYPE_NOT_SUPPORTED: 0x08,
}

const SOCKS_VER = {
  V5: 0x05,
  V4: 0x04
};

// https://github.com/rvagg/node-errno/blob/master/errno.js

const ErrorCode = new Map();
ErrorCode.set('ECONNABORTED', REPLY_CODE.CONNECTION_NOT_ALLOWED);
ErrorCode.set('ECONNRESET', REPLY_CODE.CONNECTION_NOT_ALLOWED);
ErrorCode.set('ECONNREFUSED', REPLY_CODE.CONNECTION_REFUSED);
ErrorCode.set('ENETUNREACH', REPLY_CODE.NETWORK_UNREACHABLE);
ErrorCode.set('EHOSTUNREACH', REPLY_CODE.HOST_UNREACHABLE);
ErrorCode.set('ENETDOWN', REPLY_CODE.NETWORK_UNREACHABLE);
ErrorCode.set('ENOTSUP', REPLY_CODE.CMD_NOT_SUPPORTED);
ErrorCode.set('EPROTONOSUPPORT', REPLY_CODE.SOCKS_SERVER_FAILURE);
ErrorCode.set('ENOTFOUND', REPLY_CODE.HOST_UNREACHABLE);
ErrorCode.set('EPROTO', REPLY_CODE.SOCKS_SERVER_FAILURE);
ErrorCode.set('EPROTOTYPE', REPLY_CODE.SOCKS_SERVER_FAILURE);
ErrorCode.set('ESHUTDOWN', REPLY_CODE.HOST_UNREACHABLE);
ErrorCode.set('EAIFAMNOSUPPORT', REPLY_CODE.ADDR_TYPE_NOT_SUPPORTED);
ErrorCode.set('EADDRNOTAVAIL', REPLY_CODE.ADDR_TYPE_NOT_SUPPORTED);

module.exports = {
  AUTHENTICATION,
  REQUEST_CMD,
  ATYP,
  REPLY_CODE,
  SOCKS_VER,
  ErrorCode
}